banner:
  charset: UTF-8

server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.mapper

com:
  neo:
    title: \u7EAF\u6D01\u7684\u5FAE\u7B11
    description: \u5206\u4EAB\u751F\u6D3B\u548C\u6280\u672F

#logging.level.org.springframework: WARN
logging:
  path: /Users/blues/dev/logs
  config: classpath:logback.xml
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR
      spring:
        springboot:
          dao: DEBUG
    mapper: info

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  datasource:
    driverClassName :  com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.3.80.43:3306/b2b_5?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true
    url: jdbc:mysql://10.3.80.43:3306/b2b0701?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username :  zj
    password :  123456

#指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
#  resources:
#    static-locations: classpath:/templates/static/


# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 127.0.0.1 # Redis服务器地址
    port: 6380 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）

  application:
    name: spirng-boot-rabbitmq

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  freemarker:
      allow-request-override: false
      allow-session-override: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      settings.number_format: 0.##
      prefix:
      request-context-attribute:
      suffix:
      cache: false
      template-loader-path: classpath:/templates/

